In [1]:
import polars as pl
import pandas as pd
import numpy as np
import catboost
import os
from datetime import date, timedelta

In [2]:
test_start_date = date(2024, 8, 1)
val_start_date = date(2024, 7, 1)
val_end_date = date(2024, 7, 31)
train_end_date = date(2024, 6, 30)
data_path = './predict-user-fresh-order/'

# Read data

In [3]:
actions_history = pl.read_parquet(os.path.join(data_path, 'actions_history'))
search_history = pl.read_parquet(os.path.join(data_path, 'search_history'))
product_information = pl.read_csv(os.path.join(data_path, 'product_information.csv'))

In [4]:
product_information.head(100)

shape: (100, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬─────────┬───────────┐
│ product_id ┆ name       ┆ brand      ┆ type       ┆ category_i ┆ category_ ┆ price   ┆ discount_ │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ d          ┆ name      ┆ ---     ┆ price     │
│ i64        ┆ str        ┆ str        ┆ str        ┆ ---        ┆ ---       ┆ f64     ┆ ---       │
│            ┆            ┆            ┆            ┆ i64        ┆ str       ┆         ┆ f64       │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═════════╪═══════════╡
│ 26176363   ┆ Развивающи ┆ Machaon    ┆ Печатная   ┆ 780        ┆ Книги     ┆ 380.0   ┆ 274.0     │
│            ┆ е тесты    ┆            ┆ книга:     ┆            ┆           ┆         ┆           │
│            ┆ (3-4 года) ┆            ┆ Развитие   ┆            ┆           ┆         ┆           │
│            ┆ (…         ┆            ┆ детей      ┆            ┆           ┆         ┆           │
│ 29898500   ┆ Mexx       ┆ Mexx       ┆ Туалетная  ┆ 117        ┆ Мужская   ┆ 2645.0  ┆ 1859.0    │
│            ┆ Туалетная  ┆            ┆ вода       ┆            ┆           ┆         ┆           │
│            ┆ вода Ice   ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ Touch …    ┆            ┆            ┆            ┆           ┆         ┆           │
│ 33967827   ┆ 64 ГБ USB  ┆ SmartBuy   ┆ USB-флеш-н ┆ 178        ┆ Флешки и  ┆ 1690.0  ┆ 469.0     │
│            ┆ Флеш-накоп ┆            ┆ акопитель  ┆            ┆ CD-R      ┆         ┆           │
│            ┆ итель USB  ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ …          ┆            ┆            ┆            ┆           ┆         ┆           │
│ 135938830  ┆ Чай        ┆ Ahmad Tea  ┆ Чай        ┆ 465        ┆ Чай       ┆ 319.0   ┆ 244.0     │
│            ┆ листовой   ┆            ┆ листовой   ┆            ┆ листовой  ┆         ┆           │
│            ┆ чёрный     ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ Ahmad Tea  ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ …          ┆            ┆            ┆            ┆           ┆         ┆           │
│ 137920686  ┆ Seagate 4  ┆ Seagate    ┆ Внешний    ┆ 615        ┆ Внешние   ┆ 28590.0 ┆ 9539.0    │
│            ┆ ТБ Внешний ┆            ┆ жесткий    ┆            ┆ жесткие   ┆         ┆           │
│            ┆ жесткий д… ┆            ┆ диск       ┆            ┆ диски     ┆         ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …       ┆ …         │
│ 499019785  ┆ Набор для  ┆ Анзор Игра ┆ Набор для  ┆ 5          ┆ Настольны ┆ 999.0   ┆ 425.0     │
│            ┆ игры в     ┆            ┆ покера     ┆            ┆ е игры    ┆         ┆           │
│            ┆ покер      ┆            ┆            ┆            ┆ для детей ┆         ┆           │
│            ┆ "Poker …   ┆            ┆            ┆            ┆           ┆         ┆           │
│ 519410131  ┆ Органайзер ┆ Baona      ┆ Органайзер ┆ 37         ┆ Товары    ┆ 1490.0  ┆ 838.0     │
│            ┆ для        ┆            ┆ для вещей  ┆            ┆ для дачи  ┆         ┆           │
│            ┆ хранения / ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ Орга…      ┆            ┆            ┆            ┆           ┆         ┆           │
│ 524083710  ┆ Футляр для ┆ O.Rissa    ┆ Футляр для ┆ 56         ┆ Очки и    ┆ 850.0   ┆ 407.0     │
│            ┆ очков на   ┆            ┆ очков      ┆            ┆ аксессуар ┆         ┆           │
│            ┆ магните    ┆            ┆            ┆            ┆ ы         ┆         ┆           │
│            ┆ му…        ┆            ┆            ┆            ┆           ┆         ┆           │
│ 533754271  ┆ БИОошейник ┆ Favorite   ┆ Антипарази ┆ 152        ┆ Уход      ┆ 280.0   ┆ 220.0     │
│            ┆ от блох и  ┆            ┆ тарное     ┆            ┆           ┆         ┆           │
│            ┆ клещей дл… ┆            ┆ средство   ┆            ┆           ┆         ┆           │
│            ┆            ┆            ┆ для …      ┆            ┆           ┆         ┆           │
│ 538213536  ┆ Вишня без  ┆ МОРОЗКО    ┆ Замороженн ┆ 910        ┆ Фрукты и  ┆ 255.0   ┆ 255.0     │
│            ┆ косточки   ┆ Green      ┆ ые ягоды   ┆            ┆ ягоды     ┆         ┆           │
│            ┆ 300 г,     ┆            ┆            ┆            ┆           ┆         ┆           │
│            ┆ Моро…      ┆            ┆            ┆            ┆           ┆         ┆           │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴─────────┴───────────┘

In [5]:
pl.read_csv(os.path.join(data_path, 'action_type_info.csv'))

shape: (6, 2)
┌─────────────┬────────────────┐
│ action_type ┆ action_type_id │
│ ---         ┆ ---            │
│ str         ┆ i64            │
╞═════════════╪════════════════╡
│ click       ┆ 1              │
│ favorite    ┆ 2              │
│ order       ┆ 3              │
│ search      ┆ 4              │
│ to_cart     ┆ 5              │
│ view        ┆ 6              │
└─────────────┴────────────────┘

In [6]:
val_start_date, val_end_date

(datetime.date(2024, 7, 1), datetime.date(2024, 7, 31))

In [7]:
val_target = (
    actions_history
    .filter(pl.col('timestamp').dt.date() >= val_start_date)
    .filter(pl.col('timestamp').dt.date() <= val_end_date)
    .select('user_id', (pl.col('action_type_id') == 3).alias('has_order'))
    .group_by('user_id')
    .agg(pl.max('has_order').cast(pl.Int32).alias('target'))
)

In [8]:
val_target.group_by('target').agg(pl.count('user_id'))

shape: (2, 2)
┌────────┬─────────┐
│ target ┆ user_id │
│ ---    ┆ ---     │
│ i32    ┆ u32     │
╞════════╪═════════╡
│ 0      ┆ 1227381 │
│ 1      ┆ 647575  │
└────────┴─────────┘

In [9]:
val_target.group_by('target').agg(pl.count('user_id')).collect_schema()

Schema([('target', Int32), ('user_id', UInt32)])

# Simple pipeline

## Feats

In [10]:
train_end_date, train_end_date - timedelta(days=30 * 4)

(datetime.date(2024, 6, 30), datetime.date(2024, 3, 2))

In [11]:
actions_aggs = {}
actions_id_to_suf = {
    1: "click",
    2: "favorite",
    3: "order",
    5: "to_cart",
}
for id_, suf in actions_id_to_suf.items():
    aggs = (
        actions_history
        .filter(pl.col('timestamp').dt.date() <= train_end_date)
        .filter(pl.col('timestamp').dt.date() >= train_end_date - timedelta(days=30 * 4))
        .filter(pl.col('action_type_id') == id_)
        .join(
            product_information
            .select('product_id', 'discount_price'),
            on='product_id',
        )
        .group_by('user_id')
        .agg(
            pl.count('product_id').cast(pl.Int32).alias(f'num_products_{suf}'),
            pl.sum('discount_price').cast(pl.Float32).alias(f'sum_discount_price_{suf}'),
            pl.max('discount_price').cast(pl.Float32).alias(f'max_discount_price_{suf}'),
            pl.max('timestamp').alias(f'last_{suf}_time'),
            pl.min('timestamp').alias(f'first_{suf}_time'),
        )
        .with_columns([
            (pl.lit(val_start_date) - pl.col(f'last_{suf}_time'))
            .dt.total_days()
            .cast(pl.Int32)
            .alias(f'days_since_last_{suf}'),
            
            (pl.lit(val_start_date) - pl.col(f'first_{suf}_time'))
            .dt.total_days()
            .cast(pl.Int32)
            .alias(f'days_since_first_{suf}'),
        ])
        .select(
            'user_id',
            f'num_products_{suf}',
            f'sum_discount_price_{suf}',
            f'max_discount_price_{suf}',
            f'days_since_last_{suf}',
            f'days_since_first_{suf}',
        )
    )
    actions_aggs[id_] = aggs

In [12]:
# search_aggs
id_ = 4
suf = 'search'
actions_aggs[id_] = (
    search_history
    .filter(pl.col('action_type_id') == id_)
    .filter(pl.col('timestamp').dt.date() <= train_end_date)
    .filter(pl.col('timestamp').dt.date() >= train_end_date - timedelta(days=30 * 4))
    .group_by('user_id')
    .agg(
        pl.count('search_query').cast(pl.Int32).alias(f'num_{suf}'),
        pl.max('timestamp').alias(f'last_{suf}_time'),
        pl.min('timestamp').alias(f'first_{suf}_time'),
    )
    .with_columns([
        (pl.lit(val_start_date) - pl.col(f'last_{suf}_time'))
        .dt.total_days()
        .cast(pl.Int32)
        .alias(f'days_since_last_{suf}'),

        (pl.lit(val_start_date) - pl.col(f'first_{suf}_time'))
        .dt.total_days()
        .cast(pl.Int32)
        .alias(f'days_since_first_{suf}'),
    ])
    .select(
        'user_id',
        f'num_{suf}',
        f'days_since_last_{suf}',
        f'days_since_first_{suf}',
    )
)

In [13]:
actions_aggs.keys()

dict_keys([1, 2, 3, 5, 4])

In [14]:
df = val_target
for _, actions_aggs_df in actions_aggs.items():
    df = (
        df
        .join(actions_aggs_df, on='user_id', how='left')
    )

In [15]:
df

shape: (1_874_956, 25)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ user_id  ┆ target ┆ num_produc ┆ sum_discou ┆ … ┆ days_since ┆ num_searc ┆ days_sinc ┆ days_sinc │
│ ---      ┆ ---    ┆ ts_click   ┆ nt_price_c ┆   ┆ _first_to_ ┆ h         ┆ e_last_se ┆ e_first_s │
│ i32      ┆ i32    ┆ ---        ┆ lick       ┆   ┆ cart       ┆ ---       ┆ arch      ┆ earch     │
│          ┆        ┆ i32        ┆ ---        ┆   ┆ ---        ┆ i32       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆ f32        ┆   ┆ i32        ┆           ┆ i32       ┆ i32       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 10082021 ┆ 0      ┆ 2          ┆ 1483.0     ┆ … ┆ 71         ┆ null      ┆ null      ┆ null      │
│ 4248564  ┆ 0      ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 5712207  ┆ 0      ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 10492556 ┆ 0      ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 10932596 ┆ 1      ┆ 49         ┆ 24263.0    ┆ … ┆ 118        ┆ 112       ┆ 13        ┆ 118       │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 10536587 ┆ 0      ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 72092    ┆ 1      ┆ 116        ┆ 38812.0    ┆ … ┆ 118        ┆ 167       ┆ 14        ┆ 118       │
│ 8535398  ┆ 0      ┆ null       ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 3858072  ┆ 1      ┆ 1          ┆ 1004.0     ┆ … ┆ 10         ┆ 9         ┆ 2         ┆ 45        │
│ 10184645 ┆ 0      ┆ 11         ┆ 6602.0     ┆ … ┆ 98         ┆ 22        ┆ 27        ┆ 118       │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
df_pd = df.to_pandas()

In [17]:
mask = df_pd.user_id % 10 <= 6

In [18]:
df_pd.columns

Index(['user_id', 'target', 'num_products_click', 'sum_discount_price_click',
       'max_discount_price_click', 'days_since_last_click',
       'days_since_first_click', 'num_products_favorite',
       'sum_discount_price_favorite', 'max_discount_price_favorite',
       'days_since_last_favorite', 'days_since_first_favorite',
       'num_products_order', 'sum_discount_price_order',
       'max_discount_price_order', 'days_since_last_order',
       'days_since_first_order', 'num_products_to_cart',
       'sum_discount_price_to_cart', 'max_discount_price_to_cart',
       'days_since_last_to_cart', 'days_since_first_to_cart', 'num_search',
       'days_since_last_search', 'days_since_first_search'],
      dtype='object')

In [19]:
cols = [
    'num_products_click', 
    'sum_discount_price_click', 'max_discount_price_click',
    'days_since_last_click', 'days_since_first_click',
    
    'num_products_favorite',
    'sum_discount_price_favorite', 'max_discount_price_favorite',
    'days_since_last_favorite', 'days_since_first_favorite',
    
    'num_products_order',
    'sum_discount_price_order', 'max_discount_price_order',
    'days_since_last_order', 'days_since_first_order',
    
    'num_products_to_cart',
    'sum_discount_price_to_cart', 'max_discount_price_to_cart',
    'days_since_last_to_cart', 'days_since_first_to_cart',
    
    'num_search',
    'days_since_last_search', 'days_since_first_search'
]

In [20]:
train_pool = catboost.Pool(
    df_pd.loc[mask, cols],
    label=df_pd.loc[mask].target,
)
eval_pool = catboost.Pool(
    df_pd.loc[~mask, cols],
    label=df_pd.loc[~mask].target,
)

In [21]:
train_pool.shape, eval_pool.shape

((1311636, 23), (563320, 23))

In [22]:
params = {
    'iterations': 2000,
    'depth': 7, 
    'learning_rate': 0.1, 
    'random_state': 1,
    'eval_metric': 'AUC',
    'loss_function': 'Logloss',
    'task_type': 'GPU',
}

In [23]:
model = catboost.CatBoost(params)
model.fit(
    train_pool, 
    eval_set=eval_pool,
    use_best_model=True,
    verbose=10,
    early_stopping_rounds=50,
)

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.7446812	best: 0.7446812 (0)	total: 64.3ms	remaining: 2m 8s
10:	test: 0.7534201	best: 0.7534201 (10)	total: 164ms	remaining: 29.7s
20:	test: 0.7551414	best: 0.7551414 (20)	total: 256ms	remaining: 24.1s
30:	test: 0.7560869	best: 0.7560869 (30)	total: 341ms	remaining: 21.7s
40:	test: 0.7565900	best: 0.7565900 (40)	total: 435ms	remaining: 20.8s
50:	test: 0.7569643	best: 0.7569643 (50)	total: 535ms	remaining: 20.5s
60:	test: 0.7572643	best: 0.7572643 (60)	total: 630ms	remaining: 20s
70:	test: 0.7574956	best: 0.7574956 (70)	total: 715ms	remaining: 19.4s
80:	test: 0.7576447	best: 0.7576447 (80)	total: 807ms	remaining: 19.1s
90:	test: 0.7577786	best: 0.7577786 (90)	total: 910ms	remaining: 19.1s
100:	test: 0.7579190	best: 0.7579190 (100)	total: 1s	remaining: 18.9s
110:	test: 0.7580191	best: 0.7580338 (108)	total: 1.09s	remaining: 18.6s
120:	test: 0.7581878	best: 0.7581878 (120)	total: 1.18s	remaining: 18.4s
130:	test: 0.7582148	best: 0.7582148 (130)	total: 1.29s	remaining: 18.4s
140:	test: 0.7582861	best: 0.7582861 (140)	total: 1.39s	remaining: 18.3s
150:	test: 0.7583631	best: 0.7583679 (148)	total: 1.48s	remaining: 18.1s
160:	test: 0.7584297	best: 0.7584355 (159)	total: 1.58s	remaining: 18s
170:	test: 0.7585004	best: 0.7585004 (170)	total: 1.68s	remaining: 18s
180:	test: 0.7585497	best: 0.7585517 (179)	total: 1.78s	remaining: 17.9s
190:	test: 0.7586382	best: 0.7586382 (190)	total: 1.87s	remaining: 17.7s
200:	test: 0.7586910	best: 0.7587065 (197)	total: 1.96s	remaining: 17.5s
210:	test: 0.7587200	best: 0.7587340 (207)	total: 2.06s	remaining: 17.5s
220:	test: 0.7587582	best: 0.7587582 (220)	total: 2.16s	remaining: 17.4s
230:	test: 0.7587887	best: 0.7587953 (227)	total: 2.25s	remaining: 17.3s
240:	test: 0.7588129	best: 0.7588186 (237)	total: 2.34s	remaining: 17.1s
250:	test: 0.7588648	best: 0.7588663 (249)	total: 2.44s	remaining: 17s
260:	test: 0.7588814	best: 0.7588939 (255)	total: 2.54s	remaining: 16.9s
270:	test: 0.7589265	best: 0.7589265 (270)	total: 2.63s	remaining: 16.8s
280:	test: 0.7589188	best: 0.7589266 (271)	total: 2.72s	remaining: 16.7s
290:	test: 0.7589220	best: 0.7589266 (271)	total: 2.81s	remaining: 16.5s
300:	test: 0.7589389	best: 0.7589536 (293)	total: 2.9s	remaining: 16.4s
310:	test: 0.7589504	best: 0.7589541 (309)	total: 2.98s	remaining: 16.2s
320:	test: 0.7589685	best: 0.7589750 (317)	total: 3.07s	remaining: 16.1s
330:	test: 0.7589671	best: 0.7589750 (317)	total: 3.16s	remaining: 15.9s
340:	test: 0.7589321	best: 0.7589781 (336)	total: 3.25s	remaining: 15.8s
350:	test: 0.7589778	best: 0.7589875 (347)	total: 3.33s	remaining: 15.7s
360:	test: 0.7590524	best: 0.7590524 (360)	total: 3.42s	remaining: 15.5s
370:	test: 0.7590419	best: 0.7590524 (360)	total: 3.5s	remaining: 15.4s
380:	test: 0.7590314	best: 0.7590524 (360)	total: 3.59s	remaining: 15.3s
390:	test: 0.7590501	best: 0.7590557 (387)	total: 3.68s	remaining: 15.1s
400:	test: 0.7590665	best: 0.7590665 (400)	total: 3.77s	remaining: 15s
410:	test: 0.7591162	best: 0.7591162 (410)	total: 3.85s	remaining: 14.9s
420:	test: 0.7591054	best: 0.7591334 (418)	total: 3.94s	remaining: 14.8s
430:	test: 0.7590899	best: 0.7591334 (418)	total: 4.02s	remaining: 14.6s
440:	test: 0.7591050	best: 0.7591334 (418)	total: 4.11s	remaining: 14.5s
450:	test: 0.7591670	best: 0.7591670 (450)	total: 4.2s	remaining: 14.4s
460:	test: 0.7591206	best: 0.7591670 (450)	total: 4.28s	remaining: 14.3s
470:	test: 0.7591422	best: 0.7591670 (450)	total: 4.37s	remaining: 14.2s
480:	test: 0.7591570	best: 0.7591670 (450)	total: 4.45s	remaining: 14.1s
490:	test: 0.7591536	best: 0.7591766 (487)	total: 4.54s	remaining: 13.9s
500:	test: 0.7592244	best: 0.7592244 (500)	total: 4.62s	remaining: 13.8s
510:	test: 0.7591958	best: 0.7592244 (500)	total: 4.7s	remaining: 13.7s
520:	test: 0.7592264	best: 0.7592271 (518)	total: 4.78s	remaining: 13.6s
530:	test: 0.7592073	best: 0.7592271 (518)	total: 4.87s	remaining: 13.5s
540:	test: 0.7591977	best: 0.7592333 (536)	total: 4.95s	remaining: 13.3s
550:	test: 0.7592184	best: 0.7592354 (546)	total: 5.03s	remaining: 13.2s
560:	test: 0.7592474	best: 0.7592869 (555)	total: 5.12s	remaining: 13.1s
570:	test: 0.7592775	best: 0.7592869 (555)	total: 5.2s	remaining: 13s
580:	test: 0.7592954	best: 0.7592954 (580)	total: 5.28s	remaining: 12.9s
590:	test: 0.7592797	best: 0.7593170 (587)	total: 5.37s	remaining: 12.8s
600:	test: 0.7592414	best: 0.7593170 (587)	total: 5.45s	remaining: 12.7s
610:	test: 0.7592460	best: 0.7593170 (587)	total: 5.53s	remaining: 12.6s
620:	test: 0.7592651	best: 0.7593170 (587)	total: 5.62s	remaining: 12.5s
630:	test: 0.7593025	best: 0.7593170 (587)	total: 5.7s	remaining: 12.4s
bestTest = 0.759316951
bestIteration = 587
Shrink model to first 588 iterations.

In [24]:
name = 'baseline1'
model.save_model(f"{name}.bin")

In [25]:
fi = model.get_feature_importance(eval_pool, prettified=True)
fi.head(50)

                     Feature Id  Importances
0      sum_discount_price_order    12.274780
1            num_products_order    12.254132
2      max_discount_price_order    11.275465
3         days_since_last_order    10.045279
4    sum_discount_price_to_cart     6.616628
5        days_since_first_order     6.421556
6          num_products_to_cart     5.727590
7       days_since_last_to_cart     4.790685
8            num_products_click     4.779528
9                    num_search     4.219211
10      days_since_first_search     3.731837
11   max_discount_price_to_cart     3.322317
12       days_since_last_search     2.656538
13        days_since_last_click     2.120807
14     days_since_first_to_cart     1.793898
15       days_since_first_click     1.442537
16     sum_discount_price_click     1.402727
17     max_discount_price_click     1.394515
18    days_since_first_favorite     0.872710
19  max_discount_price_favorite     0.861481
20        num_products_favorite     0.798836
21     days_since_last_favorite     0.722440
22  sum_discount_price_favorite     0.474502

In [26]:
test_users_submission = (
    pl.read_csv(os.path.join(data_path, 'test_users.csv'))
)

In [27]:
val_end_date, val_end_date - timedelta(days=30 * 4)

(datetime.date(2024, 7, 31), datetime.date(2024, 4, 2))

In [28]:
actions_aggs = {}
actions_id_to_suf = {
    1: "click",
    2: "favorite",
    3: "order",
    5: "to_cart",
}
for id_, suf in actions_id_to_suf.items():
    aggs = (
        actions_history
        .filter(pl.col('timestamp').dt.date() <= val_end_date)
        .filter(pl.col('timestamp').dt.date() >= val_end_date - timedelta(days=30 * 4))
        .filter(pl.col('action_type_id') == id_)
        .join(
            product_information
            .select('product_id', 'discount_price'),
            on='product_id',
        )
        .group_by('user_id')
        .agg(
            pl.count('product_id').cast(pl.Int32).alias(f'num_products_{suf}'),
            pl.sum('discount_price').cast(pl.Float32).alias(f'sum_discount_price_{suf}'),
            pl.max('discount_price').cast(pl.Float32).alias(f'max_discount_price_{suf}'),
            pl.max('timestamp').alias(f'last_{suf}_time'),
            pl.min('timestamp').alias(f'first_{suf}_time'),
        )
        .with_columns([
            (pl.lit(test_start_date) - pl.col(f'last_{suf}_time'))
            .dt.total_days()
            .cast(pl.Int32)
            .alias(f'days_since_last_{suf}'),
            
            (pl.lit(test_start_date) - pl.col(f'first_{suf}_time'))
            .dt.total_days()
            .cast(pl.Int32)
            .alias(f'days_since_first_{suf}'),
        ])
        .select(
            'user_id',
            f'num_products_{suf}',
            f'sum_discount_price_{suf}',
            f'max_discount_price_{suf}',
            f'days_since_last_{suf}',
            f'days_since_first_{suf}',
        )
    )
    actions_aggs[id_] = aggs

In [29]:
# search_aggs
id_ = 4
suf = 'search'
actions_aggs[id_] = (
    search_history
    .filter(pl.col('action_type_id') == id_)
    .filter(pl.col('timestamp').dt.date() <= val_end_date)
    .filter(pl.col('timestamp').dt.date() >= val_end_date - timedelta(days=30 * 4))
    .group_by('user_id')
    .agg(
        pl.count('search_query').cast(pl.Int32).alias(f'num_{suf}'),
        pl.max('timestamp').alias(f'last_{suf}_time'),
        pl.min('timestamp').alias(f'first_{suf}_time'),
    )
    .with_columns([
        (pl.lit(test_start_date) - pl.col(f'last_{suf}_time'))
        .dt.total_days()
        .cast(pl.Int32)
        .alias(f'days_since_last_{suf}'),

        (pl.lit(test_start_date) - pl.col(f'first_{suf}_time'))
        .dt.total_days()
        .cast(pl.Int32)
        .alias(f'days_since_first_{suf}'),
    ])
    .select(
        'user_id',
        f'num_{suf}',
        f'days_since_last_{suf}',
        f'days_since_first_{suf}',
    )
)

In [30]:
df = test_users_submission
for _, actions_aggs_df in actions_aggs.items():
    df = (
        df
        .join(actions_aggs_df, on='user_id', how='left')
    )

In [31]:
df_pd = df.to_pandas()

In [32]:
df_pd.shape

(2068424, 24)

In [33]:
df_pd['predict'] = model.predict(df_pd[cols], prediction_type="Probability")[:, 1]

In [34]:
df_pd[['user_id', 'predict']]

          user_id   predict
0            1342  0.196968
1            9852  0.814203
2           10206  0.222463
3           11317  0.220989
4           13289  0.633537
...           ...       ...
2068419  11157283  0.224383
2068420  11160395  0.133542
2068421  11165052  0.590410
2068422  11168218  0.529186
2068423  11172313  0.495766

[2068424 rows x 2 columns]

In [35]:
df_pd[['user_id', 'predict']].to_csv('baseline1_submission.csv', index=False)