In [3]:
import pandas as pd
import os

In [11]:
df_actions = pd.DataFrame()

for file in os.listdir('./predict-user-fresh-order/actions_history'):
    if file == "_SUCCESS":
        continue
    df_tmp = pd.read_parquet(f'./predict-user-fresh-order/actions_history/{file}')
    df_actions = pd.concat([df_actions, df_tmp])

In [20]:
df_actions.head()

,user_id,timestamp,product_id,page_product_id,action_type_id,widget_name_id
0,1130526,2024-06-02 07:19:51,351873991,NaN,5,22
1,6790904,2024-07-08 13:35:23,688372347,NaN,5,22
2,5082244,2024-06-08 13:25:02,690589601,NaN,5,22
3,1167610,2024-04-07 09:50:11,1040208709,NaN,5,22
4,6558715,2024-03-06 18:47:52,32933713,NaN,5,22

In [16]:
df_search_history = pd.DataFrame()

for file in os.listdir('./predict-user-fresh-order/search_history'):
    if file == "_SUCCESS":
        continue
    df_tmp = pd.read_parquet(f'./predict-user-fresh-order/search_history/{file}')
    df_search_history = pd.concat([df_search_history, df_tmp])

In [21]:
df_search_history.head()

,user_id,timestamp,search_query,action_type_id,widget_name_id
0,2196785,2024-06-20 20:54:36,вода,4,24
1,10577554,2024-03-16 10:16:18,молоко,4,24
2,5649193,2024-07-12 18:28:46,белый красивый топ,4,24
3,3898950,2024-04-10 14:42:23,масло сливочное,4,24
4,6385723,2024-03-18 04:29:58,нескафе дольче густо капсулы,4,24